export const LOAD_WEEK_SCHEDULE = 'LOAD_WEEK_SCHEDULE'
export const UPDATE_WEEK_SCHEDULE = 'UPDATE_WEEK_SCHEDULE'
export const LOAD_ALL_STAFF = 'LOAD_ALL_STAFF'
export const  LOAD_USER_INFORMATION = 'LOAD_USER_INFORMATION'
export const  LOAD_ORDER_HISTORY = 'LOAD_ORDER_HISTORY'
export const LOAD_STAFF_LIST = "LOAD_STAFF_LIST"
export const LOAD_EXIST_APPOINTMENT ="LOAD_EXIST_APPOINTMENT"
export const LOAD_NOTIFICATION = "LOAD_NOTIFICATION"